# Generated by Django 5.2.7 on 2025-10-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_hierarchy_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hierarchy_rank',
            field=models.PositiveIntegerField(default=999, unique=True),
        ),
    ]
