# Generated by Django 5.2.7 on 2025-10-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_hierarchy_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hierarchy_rank',
            new_name='employee_code'
        ),
    ]